name: arduino_module
services:
  arduino_module:
    container_name: arduino_module
    image: ${IMAGE}
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ${IMAGE}:latest
        - ${IMAGE}:dev
    command: python -m arduino_rest_node --port 2000
    privileged: true
    env_file: .env
    volumes:
      - ${DEVICE}:/dev/ttyACM0
    ports:
      - 2000:2000

  #####################
  # WEI Core Services #
  #####################
  wei_server:
    image: ghcr.io/ad-sdl/wei
    container_name: wei_server
    ports:
      - 8000:8000
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1 # Fix weird bug with empty logging
    volumes:
      - ${WORKCELLS_DIR}:/workcell_defs
    command: python3 -m wei.server --workcell /workcell_defs/${WORKCELL_FILENAME}
    depends_on:
      - wei_redis
    profiles: [wei]
  wei_engine:
    image: ghcr.io/ad-sdl/wei
    container_name: wei_engine
    volumes:
      - ${WORKCELLS_DIR}:/workcell_defs
    env_file: .env
    environment:
     - PYTHONUNBUFFERED=1 # Fix weird bug with empty logging
    command: python3 -m wei.engine --workcell /workcell_defs/${WORKCELL_FILENAME}
    depends_on:
      - wei_redis
      - wei_server
    profiles: [wei]
  wei_redis:
    image: redis
    container_name: wei_redis
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning
    profiles: [wei]
