name: Create New Module Repo

# Only run when the new module is created
on: create

jobs:
    rename:
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                # by default, it uses a depth of 1
                # this fetches all history so that we can read each commit
                fetch-depth: 0
                ref: ${{ github.head_ref }}

            - run: echo "$(echo '${{ github.repository }}' | awk -F '/' '{print $2}' | tr '-' '_')" >> $GITHUB_ENV
              shell: bash

            - run: echo "REPOSITORY_OWNER=$(echo '${{ github.repository }}' | awk -F '/' '{print $1}')" >> $GITHUB_ENV
              shell: bash

            - run: |
                replacement_string="$(echo '${{ github.repository }}' | awk -F '/' '{print $2}' | tr '-' '_') | tr '[:upper:]' '[:lower:]"
                replacement_string="${replacement_string%_module}"
                .github/rename.sh python_template "$replacement_string"

            - name: Git Commit/Push Changes
              uses: actions-x/commit@v1
